
name: Waka Flow

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaTimeBox
    runs-on: ubuntu-latest
    steps: 
      - uses: Hephaest/WakaTimeBox@v4.0.9
