
name: Waka Flow

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaTimeBox
    runs-on: ubuntu-latest
    steps: 
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Create README.md
        uses: actions-js/profile-readme@master
        with:
          username: makis-san
          template: 'TEMPLATE.MD'
          github_token: ${{ secrets.GH_TOKEN }}
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          template: './TEMPLATE.MD'
          github_token: ${{ secrets.GH_TOKEN }}
  todoist-stats:
      name: Update todoist stats
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: abhisheknaiidu/todoist-readme@master
          with:
            TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
            PREMIUM: ""
